# vi: set ft=Dockerfile :

FROM ruby:2.6.4

ENV LANG C.UTF-8
ENV TZ=Asia/Tokyo

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && \
    apt-get install -y build-essential \
                        libpq-dev \
                        nodejs \
                        yarn

RUN mkdir /app
ENV APP_ROOT /app
WORKDIR $APP_ROOT

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install --clean -j `nproc`

COPY . $APP_ROOT
RUN yarn install --check-files

RUN rm -rf tmp/sockets
RUN mkdir -p tmp/sockets

CMD bundle exec puma
